apiVersion: v1
kind: ConfigMap
metadata:
  name: v4-0-config-system-cliconfig
  labels:
    {{- include "oauth-server.labels" . | nindent 4 }}
data:
  v4-0-config-system-cliconfig: |
    {
        "admission":{
            
        },
        "apiVersion":"osin.config.openshift.io/v1",
        "auditConfig":{
            "auditFilePath":"",
            "enabled":false,
            "logFormat":"",
            "maximumFileRetentionDays":0,
            "maximumFileSizeMegabytes":0,
            "maximumRetainedFiles":0,
            "policyConfiguration":null,
            "policyFile":"",
            "webHookKubeConfig":"",
            "webHookMode":""
        },
        "corsAllowedOrigins":[
            "//127\\.0\\.0\\.1(:|$)",
            "//localhost(:|$)"
        ],
        "kind":"OsinServerConfig",
        "kubeClientConfig":{
            "connectionOverrides":{
                "acceptContentTypes":"",
                "burst":400,
                "contentType":"",
                "qps":400
            },
            "kubeConfig":""
        },
        "oauthConfig":{
            "alwaysShowProviderSelection":false,
            "assetPublicURL":"https://console.apps.{{ .Values.clusterDomain }}",
            "grantConfig":{
                "method":"deny",
                "serviceAccountMethod":"prompt"
            },
            "identityProviders":[
                {
                    "challenge":true,
                    "login":true,
                    "mappingMethod":"claim",
                    "name":"ldap-infra",
                    "provider":{
                        "apiVersion":"osin.config.openshift.io/v1",
                        "attributes":{
                            "email":[
                                "mail"
                            ],
                            "id":[
                                "dn"
                            ],
                            "name":[
                                "displayName"
                            ],
                            "preferredUsername":[
                                "uid"
                            ]
                        },
                        "bindDN":"uid=ose-service,cn=users,cn=accounts,dc=solution,dc=sbt",
                        "bindPassword":{
                            "env":"",
                            "file":"/var/config/user/idp/0/secret/v4-0-config-user-idp-0-bind-password/bindPassword",
                            "keyFile":"",
                            "value":""
                        },
                        "ca":"",
                        "insecure":true,
                        "kind":"LDAPPasswordIdentityProvider",
                        "url":"ldap://sp-prod-dns-infra-01.solution.sbt/cn=users,cn=accounts,dc=solution,dc=sbt?uid"
                    }
                }
            ],
            "loginURL":"https://api.{{ .Values.clusterDomain }}:6443",
            "masterCA":"/var/config/system/configmaps/v4-0-config-system-service-ca/service-ca.crt",
            "masterPublicURL":"https://oauth-console.apps.{{ .Values.clusterDomain }}",
            "masterURL":"https://oauth-console.{{ .Release.Namespace }}.svc:6443",
            "sessionConfig":{
                "sessionMaxAgeSeconds":300,
                "sessionName":"ssn",
                "sessionSecretsFile":"/var/config/system/secrets/v4-0-config-system-session/v4-0-config-system-session"
            },
            "templates":{
                "error":"/var/config/system/secrets/v4-0-config-system-ocp-branding-template/errors.html",
                "login":"/var/config/system/secrets/v4-0-config-system-ocp-branding-template/login.html",
                "providerSelection":"/var/config/system/secrets/v4-0-config-system-ocp-branding-template/providers.html"
            },
            "tokenConfig":{
                "accessTokenMaxAgeSeconds":86400,
                "authorizeTokenMaxAgeSeconds":300
            }
        },
        "servingInfo":{
            "bindAddress":"0.0.0.0:6443",
            "bindNetwork":"tcp",
            "certFile":"/var/config/system/secrets/v4-0-config-system-serving-cert/tls.crt",
            "keyFile":"/var/config/system/secrets/v4-0-config-system-serving-cert/tls.key",
            "cipherSuites":[
                "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
                "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
            ],
            "maxRequestsInFlight":1000,
            "minTLSVersion":"VersionTLS12",
            "namedCertificates":[
                {
                    "certFile":"/var/config/system/secrets/v4-0-config-system-router-certs/tls.crt",
                    "keyFile":"/var/config/system/secrets/v4-0-config-system-router-certs/tls.key",
                    "names":[
                        "*.apps.{{ .Values.clusterDomain }}"
                    ]
                }
            ],
            "requestTimeoutSeconds":300
        },
        "storageConfig":{
            "ca":"",
            "certFile":"",
            "keyFile":"",
            "storagePrefix":""
        }
    }
