kind: Secret
apiVersion: v1
metadata:
  name: v4-0-config-user-idp-0-bind-password
data:
  bindPassword: QzZzOTNMeThjaEdhbURz
type: Opaque
---
kind: OAuthClient
apiVersion: oauth.openshift.io/v1
metadata:
  name: kubernetes-console
secret: hlW2pGGraHDuMAZ4qFEKg2fUHHxr8acDEgDEcIg7RX0U7A9
redirectURIs:
  - 'https://console.apps.{{ .Values.clusterDomain }}/auth/callback' # -
  - 'https://console.apps.{{ .Values.clusterDomain }}/oauth/callback'
grantMethod: auto
---
kind: OAuthClient
apiVersion: oauth.openshift.io/v1
metadata:
  name: openshift-browser-client
secret: RMKESA5JUsPoHFFtaVfcDfHAnrSZ2zAcqU3uGRzPLj4
redirectURIs:
  - 'https://oauth-console.apps.{{ .Values.clusterDomain }}/oauth/token/display'
grantMethod: auto
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - ldap:
        attributes:
          email:
            - mail
          id:
            - dn
          name:
            - displayName
          preferredUsername:
            - uid
        bindDN: 'uid=ose-service,cn=users,cn=accounts,dc=solution,dc=sbt'
        bindPassword:
          name: ldap-secret
        insecure: true
        url: ldap://sp-prod-dns-infra-01.solution.sbt/cn=users,cn=accounts,dc=solution,dc=sbt?uid
      mappingMethod: claim
      name: ldap-infra
      type: LDAP
