kind: Secret
apiVersion: v1
metadata:
  name: v4-0-config-system-session
  labels:
    app: oauth-openshift
data:
  v4-0-config-system-session: eyJraW5kIjoiU2Vzc2lvblNlY3JldHMiLCJhcGlWZXJzaW9uIjoib3BlcmF0b3J2MWNsaWVudCIsInNlY3JldHMiOlt7ImF1dGhlbnRpY2F0aW9uIjoiSHNOM3NnOUtTZVdjYkhTUXNfWk9XcnpXZ0xtbGtsbXA3by1zN2plRTI4eXlGMmdvdS1Ed3ZRcTFsRzNmTUhSVyIsImVuY3J5cHRpb24iOiJYQmtaaWJUNko3eVNPWmZtOElvZnFXUXRRLWNQblE1SCJ9XX0=
type: Opaque
