{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "oauth-server.fullname" . }}
  labels:
    {{- include "oauth-server.labels" . | nindent 4 }}
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  selector:
    matchLabels:
      {{- include "oauth-server.selectorLabels" . | nindent 6 }}
{{- end }}
